"""purchaseproductlink remove pk bad idea

Revision ID: 1c850c7e59d7
Revises: 57ac76ea9c69
Create Date: 2023-12-25 20:01:07.437239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c850c7e59d7'
down_revision: Union[str, None] = '57ac76ea9c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchaseproductlink', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchaseproductlink', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
