"""create_currency_model

Revision ID: 285d6f51ad86
Revises: 2ef5d346c952
Create Date: 2024-01-15 15:35:25.391630

"""
from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "285d6f51ad86"
down_revision: Union[str, None] = "2ef5d346c952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_usd", sa.Numeric(scale=2), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currency_id"), "currency", ["id"], unique=False)

    op.bulk_insert(
        sa.table(
            "currency",
            sa.column("name"),
            sa.column("to_usd"),
            sa.column("symbol"),
            sa.column("code"),
        ),
        [
            {
                "name": "Dollar",
                "to_usd": 1.0,
                "symbol": "$",
                "code": "USD",
                "created_at": datetime(2024, 1, 15, 15, 35, 25, 391630),
                "updated_at": datetime(2024, 1, 15, 15, 35, 25, 391630),
            },
            {
                "name": "Bolivar",
                "to_usd": 35.92,
                "symbol": "Bs.",
                "code": "VES",
                "created_at": datetime(2024, 1, 15, 15, 35, 25, 391630),
                "updated_at": datetime(2024, 1, 15, 15, 35, 25, 391630),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currency_id"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
