"""init

Revision ID: 2f721c3a6ca1
Revises:
Create Date: 2023-12-21 20:45:24.994302

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f721c3a6ca1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("category",
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("company",
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("product",
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("price", sa.Numeric(scale=2), nullable=False),
    sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("category_id", sa.Integer(), nullable=True),
    sa.Column("company_id", sa.Integer(), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["category_id"], ["category.id"], ),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("purchase",
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("price", sa.Numeric(scale=2), nullable=False),
    sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("category_id", sa.Integer(), nullable=True),
    sa.Column("company_id", sa.Integer(), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["category_id"], ["category.id"], ),
    sa.ForeignKeyConstraint(["company_id"], ["company.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("purchaseproductlink",
    sa.Column("purchase_id", sa.Integer(), nullable=False),
    sa.Column("product_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["product_id"], ["product.id"], ),
    sa.ForeignKeyConstraint(["purchase_id"], ["purchase.id"], ),
    sa.PrimaryKeyConstraint("purchase_id", "product_id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchaseproductlink")
    op.drop_table("purchase")
    op.drop_table("product")
    op.drop_table("company")
    op.drop_table("category")
    # ### end Alembic commands ###
