"""remove base models

Revision ID: 45decc0cb8eb
Revises: 2f721c3a6ca1
Create Date: 2023-12-21 22:08:02.462462

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "45decc0cb8eb"
down_revision: Union[str, None] = "2f721c3a6ca1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchase", sa.Column("amount", sa.Numeric(scale=2), nullable=False))
    op.drop_constraint("purchase_ibfk_1", "purchase", type_="foreignkey")
    op.drop_column("purchase", "image")
    op.drop_column("purchase", "description")
    op.drop_column("purchase", "category_id")
    op.drop_column("purchase", "name")
    op.drop_column("purchase", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchase", sa.Column("price", mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.add_column("purchase", sa.Column("name", mysql.VARCHAR(length=255), nullable=False))
    op.add_column("purchase", sa.Column("category_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column("purchase", sa.Column("description", mysql.VARCHAR(length=255), nullable=False))
    op.add_column("purchase", sa.Column("image", mysql.VARCHAR(length=255), nullable=False))
    op.create_foreign_key("purchase_ibfk_1", "purchase", "category", ["category_id"], ["id"])
    op.drop_column("purchase", "amount")
    # ### end Alembic commands ###
