"""remove amount from purchase

Revision ID: 537e9aca720b
Revises: f1be87d5cf1e
Create Date: 2023-12-24 19:36:26.362013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '537e9aca720b'
down_revision: Union[str, None] = 'f1be87d5cf1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('amount', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    # ### end Alembic commands ###
