"""add_barcode_product

Revision ID: 772c096fabd8
Revises: d068b52fa130
Create Date: 2024-01-22 19:23:05.098635

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "772c096fabd8"
down_revision: Union[str, None] = "d068b52fa130"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "barcode",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "barcode")
    # ### end Alembic commands ###
