"""add m2m relation

Revision ID: 80abfa89620b
Revises: bd179b816b1e
Create Date: 2023-12-24 13:55:48.086654

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "80abfa89620b"
down_revision: Union[str, None] = "bd179b816b1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
