"""update image field

Revision ID: 91288541434c
Revises: 2ef5d346c952
Create Date: 2023-12-31 14:47:46.182078

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91288541434c"
down_revision: Union[str, None] = "2ef5d346c952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "image", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "image", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
