"""remove base models

Revision ID: bd179b816b1e
Revises: 45decc0cb8eb
Create Date: 2023-12-21 22:08:02.462462

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bd179b816b1e"
down_revision: Union[str, None] = "45decc0cb8eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
