"""add_stock_product

Revision ID: d068b52fa130
Revises: 285d6f51ad86
Create Date: 2024-01-22 19:14:37.497813

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d068b52fa130"
down_revision: Union[str, None] = "285d6f51ad86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("stock", sa.Numeric(scale=2), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "stock")
    # ### end Alembic commands ###
